import { pgEnum, pgTable, serial, text, timestamp, uuid, varchar } from "drizzle-orm/pg-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const roleEnum = pgEnum("role", ["user", "admin"]);

export const users = pgTable("users", {
  /**
   * Primary key. UUID generated by the database.
   * Use this for relations between tables.
   */
  id: uuid("id").primaryKey().defaultRandom(),
  /** Email address for email/password authentication. Unique per user. */
  email: varchar("email", { length: 320 }).unique(),
  /** Bcrypt hash of the user's password */
  passwordHash: varchar("password_hash", { length: 255 }),
  /** Google OAuth identifier. Unique per user. */
  googleId: varchar("google_id", { length: 255 }).unique(),
  /** Apple OAuth identifier. Unique per user. */
  appleId: varchar("apple_id", { length: 255 }).unique(),
  name: text("name"),
  loginMethod: varchar("login_method", { length: 64 }),
  role: roleEnum("role").default("user").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
  lastSignedIn: timestamp("last_signed_in").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

// TODO: Add your tables here
